version: '2.6.1'
services:
  leaderboard_db:
    image: postgres
    env_file: .env.development
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  leaderboard:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bundle exec sidekiq && rake users:start_update_random_user_job"
    volumes:
      - .:/leaderboard
    ports:
      - "3000:3000"
    depends_on:
      - leaderboard_db
    env_file: .env.development
volumes:
  postgres: