version: '2.6.1'
services:
  leaderboard_db:
    container_name: leaderboard_db
    image: postgres
    env_file: .env.production
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5099:5432"
  leaderboard:
    container_name: leaderboard
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/leaderboard
    ports:
      - "3000:3000"
    depends_on:
      - leaderboard_db
    env_file: .env.production
volumes:
  postgres: